//
//  PUSH.h
//  SuperG
//
//

#import "SuperG.h"

/** Handles push notifications */
@interface PUSH : SuperG

/** Register device to message service. */
+ (void) register;

/** After a succesfull registration, a push token in generated.
 @param pushToken The token generated by the messagign service conected with the device
 */
+ (void) didRegister:(NSData *)pushToken;

/**
 Handles message.
@param userInfo An NSDictionary holding the information of the push message.
@param state The state the application is in.
 */
+(void)handle:(NSDictionary *)userInfo State:(UIApplicationState)state;
@end